# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [ ]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix



## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [ ]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [ ]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v



## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [ ]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)



### Resultados

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Resultado

En base a la solucion del codigo que esta a continuacion logramos observar que la matriz SI ES HERMITIANA

A continuacion sacamos los valores

$$ \mathbf{Eigenvalues} = [4.44948974-6.70989255e-17j ,  -0.44948974+1.15877743e-17j] $$




In [2]:
import numpy as np

# Definir la matriz
A = np.array([[3, 2+1j],
              [2-1j, 1]])

# Calcular la adjunta de la matriz
A_conj_transpose = np.conj(A.T)

# Verificar si A es hermitiana
if np.array_equal(A, A_conj_transpose):
    print("La matriz es hermitiana.")
else:
    print("La matriz no es hermitiana.")

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

La matriz es hermitiana.
Eigenvalues: [ 4.44948974-6.70989255e-17j -0.44948974+1.15877743e-17j]
Eigenvectors:
 [[ 0.83912106+0.j         -0.48651894-0.24325947j]
 [ 0.48651894-0.24325947j  0.83912106+0.j        ]]



## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Respuesta

Segun la solucion del codigo que esta a continuacion se puede comprobar que SI ES UNITARIA

Al realizar la accion de una sobre la otra se puede observar que da la matriz identidad por lo que se confirama que es unitaria

 $ UU^\dagger = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $




In [5]:
import numpy as np

# Definir la matriz
U = np.array([[1/np.sqrt(2), 1j/np.sqrt(2)],
              [1j/np.sqrt(2), 1/np.sqrt(2)]])

# Calcular la adjunta de la matriz
U_conj_transpose = np.conj(U.T)

# Calcular la inversa de la matriz
U_inv = np.linalg.inv(U)

# Verificar si U es unitaria
if np.allclose(U_conj_transpose, U_inv):
    print("La matriz es unitaria.")
else:
    print("La matriz no es unitaria.")

unitaria = np.dot(U,U_conj_transpose)

unitaria


La matriz es unitaria.


array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Resultado

Segun el codigo que esta a continuacion la solucion a este problema seria

$ \mathbf{v} \otimes \mathbf{w} = \begin{bmatrix} 3 -i \\ 3 + 3i \\ -5i \\ 6-3i \end{bmatrix} $


In [6]:
M1 = np.array([[1+1j], [2-1j]])
M2 = np.array([[1-2j], [3]])

tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[3.-1.j],
       [3.+3.j],
       [0.-5.j],
       [6.-3.j]])

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Resultado

Segun el codigo que esta a continuacion la solucion a este problema seria

 $$ M_1 \otimes M_2 = \begin{bmatrix} 0 & 0 & i & 0 \\ 0 & 0 & 0 & -i \\ i & 0 & 0 & 0 \\ 0 & -i & 0 & 0 \end{bmatrix} $$


In [7]:
M1 = np.array([[0,1], [1,0]])
M2 = np.array([[1j,0], [0,-1j]])

tensor_product_m = np.kron(M1, M2)

tensor_product_m

array([[0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
       [0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j]])

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Resultado

Al realizar las operaciones con ayuda del siguiente codigo llegamos a la conclucion que la solucion es:

\begin{bmatrix}  1 \\ 0  \end{bmatrix}

In [9]:
import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1, 0])
H = np.array([[1, 1], [1, -1]])*1/np.sqrt(2)
X = np.array([[0, 1], [1, 0]])

estado0= v1

estado1=np.dot(estado0,H)

estado2=np.dot(estado1,X)

estado3=np.dot(estado2,H)

estado3



array([1., 0.])

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)

# Respuesta

Al realizar los calculos con ayuda del programa a continuacion, llegamos a la respuesta de

\begin{bmatrix}  0 \\ 0 \\ -0.70710678 \\ 0.70710678  \end{bmatrix}


In [11]:
import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1, 0])
v2 = np.array([0, 1])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)


H = np.array([[1, 1], [1, -1]])*1/np.sqrt(2)

# Calculate the tensor product
tensor_product_m = np.kron(H, H)

estado1=np.dot(tensor_product_m,tensor_product_v)


uf=np.array([[0, 1, 0, 0], [1, 0, 0, 0],[0, 0, 1, 0],[0, 0, 0, 1]])

estado2=np.dot(estado1,uf)

estado2

identidad= np.array([[1,0],[0,1]])

estado3=np.dot(np.kron(H,identidad),estado2)

estado3

array([ 0.        ,  0.        , -0.70710678,  0.70710678])